# Read bulk tissue data of Arabidopsis root.
# Read bulk tissue data of Arabidopsis root.
bulk_dat <- function(rds, cnt.path, meta.path, marker.blk.path, dev.zone=FALSE) {
  library(readr)
  if (file.exists(rds)) { bulk <- readRDS(rds); return(bulk) } 
  met <- read.table(meta.path, header=TRUE, sep=',')
  # Metadata of bulk data.
  met.li <- subset(met, Reference=='Li et al. 2016')
  w <- which(met.li$Filename %in% c('SRR3664374_counts.txt', 'SRR3664375_counts.txt', 'SRR3664437_counts.txt'))
  met.li[w, 'Marker'] <- 'COR'
  marker <- met.li$Marker; names(marker) <- met.li$Filename
  marker <- marker[!marker %in% c('Elongation', 'Maturation', 'Meristematic', 'Whole_Root')]
  marker <- marker[sort(names(marker))]

  # Bulk data
  cnt <- as.data.frame(read_csv(cnt.path))
  rownames(cnt) <- cnt$Locus
  cnt.li <- cnt[, colnames(cnt) %in% met.li$Filename]
  cnt.li <- cnt.li[, names(marker)]
  colnames(cnt.li) <- marker

  # Bulk data sample names.
  marker.bulk <- read.table(marker.blk.path, header=TRUE, sep='\t')
  colnames(marker.bulk) <- make.names(marker.bulk[1, ])
  marker.bulk <- marker.bulk[-1, ]

  short.na <- marker.bulk$short.name
  names(short.na) <- marker.bulk$marker.name
  short.na <- short.na[marker]
  # Assign sample names to bulk data.
  colnames(cnt.li) <- short.na[colnames(cnt.li)]
  # Should not re-order columns by sorted column names, since duplicated values are created even though use as.matix to retain identical column names.
  # cnt.li <- as.matrix(cnt.li)[, sort(colnames(cnt.li))]
  cna.all <- colnames(cnt.li) 
  if (dev.zone==FALSE) cna.all <- sub('^MAT_|^DEV_', '', cna.all)
  vec1 <- c('COLUMELLA', 'PERICYCLE'); vec2 <- c('COLU', 'PERI')
  for (i in seq_along(vec1)) cna.all <- sub(vec1[i], vec2[2], cna.all)
  colnames(cnt.li) <- cna.all
  saveRDS(cnt.li, file=rds); return(cnt.li)
}
# Mouse kidney bull tissues.
blk_dat_mus_kdn <- function(pa=NULL, glom.pa1=NULL, glom.pa2=NULL) {
  library(data.table)
  blk.kdn <- fread(pa); rna <- blk.kdn$Gene_symbol
  blk.kdn <- round(as(blk.kdn[, -1], 'matrix'))
  rownames(blk.kdn) <- rna
  cna <- gsub('(.*_)(.*)(_.*)', '\\2', colnames(blk.kdn))
  colnames(blk.kdn) <- cna
  # Glomeruli.
  glom1 <- fread(glom.pa1); rna.g1 <- glom1$V1
  glom1 <- as(glom1[, -1], 'matrix'); colnames(glom1) <- 'GLOM'
  rownames(glom1) <- rna.g1
  glom2 <- fread(glom.pa2); rna.g2 <- glom2$V1
  glom2 <- as(glom2[, -1], 'matrix'); colnames(glom2) <- 'GLOM'
  rownames(glom2) <- rna.g2
  identical(rownames(glom1), rownames(glom2))
  inter <- intersect(rownames(blk.kdn), rownames(glom1)) 
  blk.kdn <- cbind(glom1[inter, , drop=FALSE], glom2[inter, , drop=FALSE], blk.kdn[inter, ])
  return(blk.kdn)
}

# Import bulk raw count data generated by systemsPipeR. 
blk_dat_mus <- function(pa=NULL) {
  library(data.table)
  blk.mus <- fread(pa); rna <- blk.mus$V1
  blk.mus <- as(blk.mus[, -1], 'matrix')
  rownames(blk.mus) <- rna; cna <- toupper(colnames(blk.mus))
  if (any(grepl('_\\d+$', cna))) colnames(blk.mus) <- sub('_\\d+$', '', cna) else if (any(grepl('\\d+$', cna))) colnames(blk.mus) <- sub('\\d+$', '', cna) 
  return(blk.mus)
}
